#ifndef FILEWATCHER_H
#define FILEWATCHER_H

#include "watchedpath.h"
#include "event.h"
#include <QFileSystemWatcher>

// will scan for files on start
// connect signals generated by QFileSystemWatcher to update EventModel
class FileWatcher
{
public:
    FileWatcher(QList<WatchedPath> paths);

private:
    QFileSystemWatcher m_watcher;
    QStringList m_filesPaths;
    QVector<Event> m_events;
};

#endif // FILEWATCHER_H
